language: python
python:
 - "3.4"

install:
 - pip install -r travis/requirements.txt
 - python setup.py install

before_script:
 - wget https://raw.githubusercontent.com/phlax/aio.app/master/travis/aio.conf
 - wget https://raw.githubusercontent.com/phlax/aio.app/master/travis/logging.conf

script: aio test aio.app
